### ISSUE TITLE
Multiline strings as function arguments produces compilation error

### ISSUE THREAD

**Issue by danbruce** [phalcon/zephir#365]
Code example

```
class MyClass
{
    public function __construct()
    {
        echo "
            Multi line string
        ";

        echo trim("
            Multi line string
        ");
    }
}
```

The first multiline string does not cause a problem. The second string causes
compilations failures (the generated C code does not properly escape the line
breaks).

The relevant C code that gets generated:

```
php_printf("\n            Multi line string\n        ");
```

for the echo and:

```
ZEPHIR_INIT_VAR(_0);
ZEPHIR_SINIT_VAR(_1);
ZVAL_STRING(&_1, "
        Multi line string
    ", 0);
zephir_fast_trim(_0, &_1, NULL , ZEPHIR_TRIM_BOTH TSRMLS_CC);
zend_print_zval(_0, 0);
```

for the echo trim(...).

Using git bisect shows b275db3f14e94470bdd7bf7ab94d28f78c955251 as the guilty commit.
